[[constraint]]
  name = "github.com/fatih/structs"
  version = "1.0.0"

[[constraint]]
  branch = "master"
  name = "github.com/hashicorp/go-multierror"

[[constraint]]
  name = "github.com/hashicorp/vault"
  version = "0.10.0"

[prune]
  go-tests = true
  unused-packages = true
